### ISSUE TITLE
TypeError: DeviceRegistry.async_get_or_create() unexpected keyword argument 'via_device_id' in v3.17.0

### ISSUE THREAD

**Issue by KeMaLiPro** [fdebrus/Nikobus-HA#507]
### Before opening

- [x] I have searched [existing issues](https://github.com/fdebrus/Nikobus-HA/issues?q=is%3Aissue) and didn't find a duplicate.
- [x] I have read the [README](https://github.com/fdebrus/Nikobus-HA#readme).

### Environment
- **Integration Version:** 3.17.0 (worked in 3.12.0)
- **Home Assistant Version:** Recent HA Core release

### Problem Description
After updating to v3.17.0, the Nikobus integration fails to set up. Home Assistant throws a `TypeError` because `via_device_id` has been deprecated/renamed to `via_device` in the Home Assistant Device Registry API.

### Logs / Traceback
```python
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'via_device_id'. Did you mean 'via_device'?

### Steps to reproduce

1. Starting up HA
2. Failed connection to hub 

### Expected vs actual behaviour

Expected: connection with hub is establisched
Actual: can't get a connection with hub

### Nikobus integration version

3.17.3

### nikobus-connect library version

0.37.3

### Home Assistant Core version

2026.7.4

### HA installation type

Home Assistant Container (Docker)

### How HA connects to the PC-Link

TCP bridge (e.g. `192.168.1.50:9999`)

### Hardware mix on the bus

2x 05-001-02 Rolluikmodule
1x 05-002-02 Compacte schakelmodule
1x 05-058 Interface voor drukknoppen
3x 05-060-01 Busdrukknop, 2 bedieningspunten
5x 05-064-02 Feedbackknop, 4 bedieningspunten
1x 05-200 PC-Link
1x 05-201 PC-Logic gebruikt als 'master'
1x 05-203 SMS-Interface 
1x 05-207 Feedback Module (met/zonder scherm) 

### Debug log

```text
I did not put into debug mode because I have already resolved the problem: additional context.
```

### Diagnostics download

- [x] I have attached the diagnostics download to this issue.

### Additional context

I adapted the code (replaced 'via_device_id' with 'via_device' in the following files:

custom_components/nikobus/__init__.py (line 548)

custom_components/nikobus/router.py (line 40)

custom_components/nikobus/button.py (line 229)

**Comment by fdebrus** [comment]
Thanks for the precise report, and sorry about this one: I was too quick to move the integration onto the latest Home Assistant release.

What happened: Home Assistant 2026.8 deprecated the `via_device` argument of the device registry in favour of `via_device_id` (removal announced for 2027.8). Release 3.15.5 switched to the new argument to clear the deprecation warning, which silently made **Home Assistant 2026.8.0 the minimum** for every release since, and nothing declared it. On 2026.7.4 the registry rejects the argument and setup fails exactly as you saw.

So the fix on your side is to update Home Assistant to 2026.8 or later. Your local patch (putting `via_device` back) works on 2026.7, but on 2026.8+ it brings the deprecation warning back, so I would rather not ship it.

On my side, the next release declares the minimum in `hacs.json` so HACS refuses to install or update the integration on an older core with a clear message instead of failing at start-up, and the README says it explicitly. Apologies again for the inconvenience.

---
_Generated by [Claude Code](https://claude.ai/code)_
